Plac3hold3r/MvxScaffolding

- MvxScaffolding.sln
- Nuget.Config
- README.md
- docs/nuget_docs.md
- nuspec/MvxScaffolding.Templates.nuspec
- src/MvxScaffolding.Vsix/MvxScaffolding.config.json
- src/MvxScaffolding.Vsix/source.extension.vsixmanifest
- src/Templates/MvxForms/src/MvxFormsTemp.Core/MvxFormsTemp.Core.csproj
- src/Templates/MvxForms/src/MvxFormsTemp.Droid/MvxFormsTemp.Droid.csproj
- src/Templates/MvxForms/src/MvxFormsTemp.UI/MvxFormsTemp.UI.csproj
- src/Templates/MvxForms/src/MvxFormsTemp.UWP/MvxFormsTemp.UWP.csproj
- src/Templates/MvxForms/src/MvxFormsTemp.iOS/MvxFormsTemp.iOS.csproj
- src/Templates/MvxForms/test/MvxFormsTemp.Core.Test/MvxFormsTemp.Core.Test.csproj
- src/Templates/MvxForms/test/MvxFormsTemp.Droid.Test/MvxFormsTemp.Droid.Test.csproj
- src/Templates/MvxForms/test/MvxFormsTemp.UI.Test/MvxFormsTemp.UI.Test.csproj
- src/Templates/MvxForms/test/MvxFormsTemp.UWP.Test/MvxFormsTemp.UWP.Test.csproj
- src/Templates/MvxNative/src/MvxNative.Core/MvxNative.Core.csproj
- src/Templates/MvxNative/src/MvxNative.Droid/MvxNative.Droid.csproj
- src/Templates/MvxNative/src/MvxNative.UWP/MvxNative.UWP.csproj
- src/Templates/MvxNative/src/MvxNative.iOS/MvxNative.iOS.csproj
- src/Templates/MvxNative/test/MvxNative.Core.Test/MvxNative.Core.Test.csproj
- src/Templates/MvxNative/test/MvxNative.Droid.Test/MvxNative.Droid.Test.csproj
- src/Templates/MvxNative/test/MvxNative.Droid.UI.Test/MvxNative.Droid.UI.Test.csproj
- src/Templates/MvxNative/test/MvxNative.UWP.Test/MvxNative.UWP.Test.csproj
- src/Templates/MvxNative/test/MvxNative.iOS.UI.Test/MvxNative.iOS.UI.Test.csproj
* Update to support MvvmCross 5.7.0
* Update Android support libraries to v27
* Update Android Target framework to v8.1
> Update to support MvvmCross 5.7.0

- src/Templates/MvxForms/src/MvxFormsTemp.Droid/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxForms/src/MvxFormsTemp.Droid/MvxFormsTemp.Droid.csproj
- src/Templates/MvxForms/src/MvxFormsTemp.Droid/proguard.cfg
- src/Templates/MvxForms/src/MvxFormsTemp.iOS/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxForms/src/MvxFormsTemp.iOS/MvxFormsTemp.iOS.csproj
- src/Templates/MvxNative/src/MvxNative.Droid/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxNative/src/MvxNative.Droid/MvxNative.Droid.csproj
- src/Templates/MvxNative/src/MvxNative.Droid/proguard.cfg
- src/Templates/MvxNative/src/MvxNative.iOS/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxNative/src/MvxNative.iOS/MvxNative.iOS.csproj
- Add Android support for proguard.cfg
- Update Android linker includes supporting full linking
- Update iOS linker includes supporting full linking
> Add Android Proguard.cfg and update linker includes

- README.md
- docs/template_dotnet_cli.md
- nuspec/MvxScaffolding.Templates.nuspec
- src/MvxScaffolding.Vsix/source.extension.vsixmanifest
* Update docs with changes
* Bump versions
> Bump version for 0.8.0 release

- README.md
- src/MvxScaffolding.VsEmulator/App.xaml.cs
- src/Templates/MvxForms/src/MvxFormsTemp.iOS/Styles/ColorPalette.cs
- src/Templates/MvxNative/src/MvxNative.iOS/Styles/ColorPalette.cs
* Improved color template error message copy
* Update translation README copy
> Update translation README copy

- README.md
- docs/nuget_docs.md
- src/Templates/MvxForms/src/MvxFormsTemp.UWP/MvxFormsTemp.UWP.csproj
- src/Templates/MvxForms/test/MvxFormsTemp.Core.Test/MvxFormsTemp.Core.Test.csproj
- src/Templates/MvxForms/test/MvxFormsTemp.UWP.Test/MvxFormsTemp.UWP.Test.csproj
- src/Templates/MvxNative/src/MvxNative.UWP/MvxNative.UWP.csproj
- src/Templates/MvxNative/test/MvxNative.Core.Test/MvxNative.Core.Test.csproj
- src/Templates/MvxNative/test/MvxNative.UWP.Test/MvxNative.UWP.Test.csproj
- Update UWP default target to SDK 17134
- Update UWP dependencies
- Update doc SDK recommendations to latest SDK versions
> Update UWP and dependency update

- README.md
- docs/nuget_docs.md
- docs/release_notes.md
- nuspec/MvxScaffolding.Templates.nuspec
- src/MvxScaffolding.UI/Views/AppDetailsView.xaml
- src/MvxScaffolding.Vsix/MvxScaffolding.Vsix.csproj
- src/Templates/MvxForms/.template.config/dotnetcli.host.json
- src/Templates/MvxNative/.template.config/dotnetcli.host.json
- src/Templates/MvxNative/.template.config/template.json
- Disabled ScaffoldType for now
- Fix HasAndroidUITestProject path
> Update release notes and bump version

- src/Templates/MvxNative/NavigationMenu/src/MvxNative.Droid/MvxNative.Droid.csproj
- src/Templates/MvxNative/SingleView/src/MvxNative.Droid/MvxNative.Droid.csproj
> Fix Android csproj referencing both AXML and XML layouts

- src/Templates/MvxNative/NavigationMenu/src/MvxNative.Droid/Views/!Base/BaseActivity.cs
> Fix native menu template toolbar assignment

- src/Templates/MvxNative/NavigationMenu/src/MvxNative.Droid/Views/Main/MainContainerActivity.cs
- Fix missing call to base OnResume and OnPasue on the MvxNative Navigation template
> Fixes for Android

- src/Templates/MvxNative/NavigationMenu/src/MvxNative.Droid/Resources/layout/fragment_main.axml
- src/Templates/MvxNative/NavigationMenu/src/MvxNative.Droid/Resources/layout/fragment_settings.axml
- src/Templates/MvxNative/SingleView/src/MvxNative.Droid/Resources/layout/fragment_main.axml
> Improve usage of Android constraints layout

- src/MvxScaffolding.Core/Contexts/MvxScaffoldingContext.cs
- src/MvxScaffolding.Core/Diagnostics/Trackers/TelemetryTracker.cs
- src/MvxScaffolding.Core/Template/ITemplateOptions.cs
- src/MvxScaffolding.Core/Template/TemplateOptions.cs
- src/MvxScaffolding.Core/ViewModels/AppDetailsViewModel.cs
- src/MvxScaffolding.Core/ViewModels/WizardOptionViewModel.cs
- src/MvxScaffolding.Localization/Resources/LocalResources.Designer.cs
- src/MvxScaffolding.Localization/Resources/LocalResources.resx
- src/MvxScaffolding.UI/Views/AppDetailsView.xaml
- src/MvxScaffolding.Vsix/MvxScaffolding.config.json
- src/MvxScaffolding.Vsix/Wizards/MvxScaffoldingBase.cs
- src/MvxScaffolding.Vsix/Wizards/MvxScaffoldingDirectoryFix.cs
> Fix directory location for solution generation

- src/Templates/MvxForms/Blank/src/MvxFormsTemp.UWP/MvxFormsTemp.UWP.csproj
- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.UWP/MvxFormsTemp.UWP.csproj
- src/Templates/MvxForms/Shared/test/MvxFormsTemp.UWP.Test/MvxFormsTemp.UWP.Test.csproj
- src/Templates/MvxForms/SingleView/src/MvxFormsTemp.UWP/MvxFormsTemp.UWP.csproj
- src/Templates/MvxNative/Blank/src/MvxNative.UWP/MvxNative.UWP.csproj
- src/Templates/MvxNative/NavigationMenu/src/MvxNative.UWP/MvxNative.UWP.csproj
- src/Templates/MvxNative/Shared/test/MvxNative.UWP.Test/MvxNative.UWP.Test.csproj
- src/Templates/MvxNative/SingleView/src/MvxNative.UWP/MvxNative.UWP.csproj
> Fix for #343 uwp target version

- src/MvxScaffolding.Core/Contexts/MvxScaffoldingContext.cs
- src/MvxScaffolding.Core/Files/FileDeleteStatus.cs
- src/MvxScaffolding.Core/Files/FileSystemUtils.cs
- src/MvxScaffolding.Core/MvxScaffolding.Core.csproj
- src/MvxScaffolding.Core/Template/TemplateLinks.cs
- src/MvxScaffolding.Core/ViewModels/Dialogs/SimpleInfoViewModel.cs
- src/MvxScaffolding.Localization/Resources/LocalResources.Designer.cs
- src/MvxScaffolding.Localization/Resources/LocalResources.resx
- src/MvxScaffolding.UI/Views/MainWindow.xaml.cs
- src/MvxScaffolding.Vsix/MvxScaffolding.config.json
- src/MvxScaffolding.Vsix/Wizards/MvxScaffoldingBase.cs
> feat(vsix): Update error handling on startup

- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.Core/MvxFormsTemp.Core.csproj
- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.Droid/MvxFormsTemp.Droid.csproj
- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.UI/MvxFormsTemp.UI.csproj
- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.UWP/MvxFormsTemp.UWP.csproj
- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.iOS/MvxFormsTemp.iOS.csproj
- src/Templates/MvxForms/Shared/test/MvxFormsTemp.Core.Test/MvxFormsTemp.Core.Test.csproj
- src/Templates/MvxForms/SingleView/src/MvxFormsTemp.Core/MvxFormsTemp.Core.csproj
- src/Templates/MvxForms/SingleView/src/MvxFormsTemp.Droid/MvxFormsTemp.Droid.csproj
- src/Templates/MvxForms/SingleView/src/MvxFormsTemp.UI/MvxFormsTemp.UI.csproj
- src/Templates/MvxForms/SingleView/src/MvxFormsTemp.UWP/MvxFormsTemp.UWP.csproj
- src/Templates/MvxForms/SingleView/src/MvxFormsTemp.iOS/MvxFormsTemp.iOS.csproj
- src/Templates/MvxNative/NavigationMenu/src/MvxNative.Core/MvxNative.Core.csproj
- src/Templates/MvxNative/NavigationMenu/src/MvxNative.Droid/MvxNative.Droid.csproj
- src/Templates/MvxNative/NavigationMenu/src/MvxNative.UWP/MvxNative.UWP.csproj
- src/Templates/MvxNative/NavigationMenu/src/MvxNative.iOS/MvxNative.iOS.csproj
- src/Templates/MvxNative/Shared/test/MvxNative.Core.Test/MvxNative.Core.Test.csproj
- src/Templates/MvxNative/SingleView/src/MvxNative.Core/MvxNative.Core.csproj
- src/Templates/MvxNative/SingleView/src/MvxNative.Droid/MvxNative.Droid.csproj
- src/Templates/MvxNative/SingleView/src/MvxNative.UWP/MvxNative.UWP.csproj
- src/Templates/MvxNative/SingleView/src/MvxNative.iOS/MvxNative.iOS.csproj
Preventing building of Android project post 6.4+
> fix(template): remove Mvx CodeAnalysis 6.4+

- src/Templates/MvxForms/Shared/test/MvxFormsTemp.UWP.Test/MvxFormsTemp.UWP.Test.csproj
- src/Templates/MvxNative/Shared/test/MvxNative.UWP.Test/MvxNative.UWP.Test.csproj
> feat(template): UWP use NuGet Microsoft.NET.Test.Sdk

- src/Templates/MvxForms/Blank/src/MvxFormsTemp.Droid/MvxFormsTemp.Droid.csproj
Reverts Plac3hold3r/MvxScaffolding#752
> Revert "chore(deps): bump MvvmCross.Droid.Support.V7.AppCompat from 6.4.2 to 6.4.3 in /src/Templates/MvxForms/Blank"

- src/Templates/MvxForms/Blank/src/MvxFormsTemp.Droid/MvxFormsTemp.Droid.csproj
Reverts Plac3hold3r/MvxScaffolding#751
> Revert "chore(deps): bump MvvmCross.Droid.Support.Design from 6.4.2 to 6.4.3 in /src/Templates/MvxForms/Blank"

- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.Droid/MvxFormsTemp.Droid.csproj
Reverts Plac3hold3r/MvxScaffolding#747
> Revert "chore(deps): bump MvvmCross.Droid.Support.Design from 6.4.2 to 6.4.3 in /src/Templates/MvxForms/NavigationMenu"

- src/Templates/MvxNative/SingleView/src/MvxNative.Droid/MvxNative.Droid.csproj
Reverts Plac3hold3r/MvxScaffolding#746
> Revert "chore(deps): bump MvvmCross.Droid.Support.Design from 6.4.2 to 6.4.3 in /src/Templates/MvxNative/SingleView"

- src/MvxScaffolding.UI/Views/MainWindow.xaml
> feat: disable window resize

- src/MvxScaffolding.Vsix/template/templatepack.MvxScaffolding.Vsix.proj
> fix: path for iTunes artwork in VSIX extension

- docs/template_dotnet_cli.md
- src/MvxScaffolding.Core/Configuration/TemplateConfig.cs
- src/Templates/MvxForms/.template.config/template.json
- src/Templates/MvxNative/.template.config/template.json
Add support for iOS 13.2-13.5
Add support for Windows SDK 2004 - April 2020 Update
> feat: update OS support [iOS + UWP]

- src/Templates/MvxForms/.template.config/template.json
- src/Templates/MvxNative/.template.config/template.json
> fix: remove duplicate key for iOS platforms

- src/Templates/MvxForms/Blank/src/MvxFormsTemp.iOS/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxForms/NavigationMenu/src/MvxFormsTemp.iOS/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxForms/SingleView/src/MvxFormsTemp.iOS/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxNative/Blank/src/MvxNative.iOS/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxNative/NavigationMenu/src/MvxNative.iOS/Linker/LinkerPleaseInclude.cs
- src/Templates/MvxNative/SingleView/src/MvxNative.iOS/Linker/LinkerPleaseInclude.cs
> Add UISearchBar to LinkerPleaseInclude.cs

- src/MvxScaffolding.UI/Views/MainWindow.xaml
> feat: make text adjust to overflow for different languages
